version: '3.9'
services:
    backend_coffeshop:
      container_name : backend_coffeshop
      image: bukanpunyamu/backend_coffeshop
      ports:
        - '8082:8081'
      
      expose:
        - 8081
      networks :
       - my_local_network
      environment :
        - DB_HOST=postgres
        - DB_PORT=5432
        - DB_NAME=coffeshop_database
        - DB_USER=ekha
        - DB_PASS=@0okmnji9!
      depends_on:
        postgres:
          condition: service_healthy


    postgres:
      image: postgres:13-alpine
      container_name: postgres
      environment:
        - POSTGRES_USER=ekha
        - POSTGRES_PASSWORD=@0okmnji9!
      volumes:
        - './postgres-data:/var/lib/postgresql/data'
      ports:
        - "5433:5432"
      expose:
        - 5432
      networks:
        - my_local_network
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ekha" ]
        interval: 10s
        timeout: 5s
        retries: 5
networks:
  my_local_network:
    driver: 'bridge'
    external: true

