-- CREATE TABLE golang.users (
--     id_user uuid NULL DEFAULT gen_random_uuid(),
--     username varchar NOT NULL,
--     "password" VARCHAR NOT NULL,
--     email VARCHAR NOT NULL UNIQUE,
--     "role" VARCHAR NOT NULL,
-- 	first_name varchar NOT NULL,
--     last_name varchar NOT NULL,
--     "address" VARCHAR NOT NULL,
--     birthday DATE NOT NULL,
--     gender VARCHAR NOT NULL,
--     created_at timestamp without time zone NOT NULL DEFAULT now(),
--     updated_at timestamp without time zone NULL,
--     CONSTRAINT user_pk PRIMARY KEY (id_user)
-- );

-- CREATE TABLE golang.categorys (
--     id_category uuid NULL DEFAULT gen_random_uuid(),
--     category_title varchar NOT NULL,
--     created_at timestamp without time zone NOT NULL DEFAULT now(),
--     updated_at timestamp without time zone NULL,
--     CONSTRAINT category_pk PRIMARY KEY (id_category)
-- );

-- CREATE TABLE golang.products (
--     id_product uuid DEFAULT gen_random_uuid() PRIMARY KEY,
--     id_category uuid,
--     banner_product varchar,
--     product_title varchar NOT NULL,
--     price int NOT NULL,
--     favorite boolean NOT NULL,
--     created_at timestamp without time zone NOT NULL DEFAULT now(),
--     updated_at timestamp without time zone,
--     CONSTRAINT product_fk FOREIGN KEY (id_category) REFERENCES golang.categorys(id_category) ON DELETE CASCADE
-- );